apiVersion: v1
kind: Service

metadata:
  name: nest-service

spec:
  type: NodePort
  selector: 
    app: backend-app
  ports:
    - protocol: TCP
      nodePort: 31000
      targetPort: 3000
      port: 3000
