apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: host-data
          mountPath: /mnt/data
  volumes:
    - name: host-data
      hostPath:
        path: /mnt/data
